#!/bin/bash
#
# MIT License
#
# Copyright (c) 2022 The Homeport Team
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -euo pipefail

CONFIG="$(cat)"
echo >&2 -e "\\033[1mConfig\\033[0m:\n$(jq -C '.source.token="***"' <<<"${CONFIG}")"

HOSTNAME="$(jq --raw-output '.source.hostname // ""' <<<"${CONFIG}")"
TOKEN="$(jq --raw-output '.source.token // ""' <<<"${CONFIG}")"
REPOSITORY="$(jq --raw-output '.source.repository // ""' <<<"${CONFIG}")"
NUMBER="$(jq --raw-output '.version.ref // ""' <<<"${CONFIG}")"

export GH_HOST="$HOSTNAME"
gh auth login --hostname "$HOSTNAME" --with-token <<<"${TOKEN}" >&2
jq . <<EOF
{
  "version": {
    "ref": "$NUMBER"
  },
  "metadata": $(gh --repo "$HOSTNAME/$REPOSITORY" issue view "$NUMBER" --json body,createdAt,number,state,title,updatedAt,url | jq '[ to_entries[] | { "name": .key, "value": .value | tostring } ]')
}
EOF
